# Setup
title:        Cologne Open Data
tagline:      Implementation of the Open Data API from the City of Cologne, Germany
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Sven
  url:        http://www.templer.se

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
